### ISSUE TITLE
LimaViewer not found

### ISSUE THREAD

**Issue by PhilLAL** [esrf-bliss/Lima#101]
Hi,
making some test with the new version installed through `conda install --channel esrf-bcu lima-camera-basler-tango`, I noticed that LimaViewer is not found anymore in the path.
I found in #86 that I already encountered this issue but I do not find any tip where to find it. 
Could you help me find it?

Regards

**Comment by laurent-claustre** [comment]
Hi Philippe,
yes, it is just missing a startup script in bin/ installation, like for LimaCCDs ($CONDA_PREFIX/bin/LimaCCDs).
I can fix and prepare a new package for lima-tango-server.

**Comment by PhilLAL** [comment]
Super! Thanks

**Comment by laurent-claustre** [comment]
Fixed since 1.9.0
