### ISSUE TITLE
configuring LImA DS with astor

### ISSUE THREAD

**Issue by PhilLAL** [esrf-bliss/Lima#105]
Hi,
with a conda installation, is there some recommandations about how to configure LImA Device server with astor?

Thank you

**Comment by laurent-claustre** [comment]
Hi Philippe,
no, sorry, we do not use astor on beamline at ESRF.

**Comment by PhilLAL** [comment]
Thank you Laurent, 
to anyone else reading this issue, if you use both astor and Lima, please let me know, I would be very interested to know how we could use both softs.

**Comment by smaluli** [comment]
Hi Philippe,

We have the same configuration here (conda + astor) and no fix yet : I'll tell you if we find something. On another side, we're testing Basler-pypylon.

**Comment by PhilLAL** [comment]
Hi there,
it seems the last update 1.9.0 (and indeed 1.9.1) make this work. 
Is this a Christmas gift in advance? :)

**Comment by laurent-claustre** [comment]
Good, so @smaluli  could you make a test?

**Comment by PhilLAL** [comment]
From my side, I confirm it works now. 
I let you close if you consider also this issue solved.

**Comment by smaluli** [comment]
Yes, sorry for the delay; it's ok from our side too!

**Comment by PhilLAL** [comment]
I think this issue can be closed.
