### ISSUE TITLE
Use camera output signal 

### ISSUE THREAD

**Issue by hayg25** [esrf-bliss/Lima#107]
Dear All, 
we are using scA640-70gm camera and we would like to use the camera output signal to switch diod light on. 
In PylonViewer, we use the menue Digital I/O, line source (User Output). 
How could we manage that in Lima ? 

Thanks for your help / feedback 
Hayg

**Comment by laurent-claustre** [comment]
Hi Hayg,

do you use the output 1 and select as source one the following source:
      Off, ExposureActive, FrameTriggerWait, LineTriggerWait,
      Timer1Active, Timer2Active, Timer3Active, Timer4Active, TimerActive,
      UserOutput1, UserOutput2, UserOutput3, UserOutput4, UserOutput,
      TriggerReady, SerialTx, AcquisitionTriggerWait, ShaftEncoderModuleOut, FrequencyConverter,
      PatternGenerator1, PatternGenerator2, PatternGenerator3, PatternGenerator4,
      AcquisitionTriggerReady,

If yes, the Basler plugin has a method setOutput1LineSource(source), but the Tango server does not export this feature. Could be simple to add a new tango attribute.  I can send you a patch.

Are you now using conda packages and latest version which is now 1.9?

**Comment by PhilLAL** [comment]
Hi Laurent,
I answer for the case Hayg wrote about, we are using 1.8 lima-core conda package, and lima-camera-basler 1.8.1 package but we can update it if you send us a patch.
Thanks :)

**Comment by laurent-claustre** [comment]
Hi @PhilLAL , yes you're right, we just push 1.9 on esrf-bcu  few hours ago.

**Comment by hayg25** [comment]
Hi Laurent, 
from the 1.9 version do we still need your patch or is it already included in the Conda package ?

**Comment by laurent-claustre** [comment]
@hayg25 Please answer to my question first, I cannot do a patch without knowing more about your need

**Comment by hayg25** [comment]
Hi @laurent-claustre,  I just checked : 
we are using  the UserOutput1source. 

Thx

**Comment by hayg25** [comment]
Hi Laurent,
any news ? :) 

Cheers

**Comment by hayg25** [comment]
Thx :)

**Comment by laurent-claustre** [comment]
Hi Hayg,
we just push new release for lima-camera-basler and lima-camera-basler-tango 1.9.1.
It provides 2 news attributes for the Basler tango device.

* **output1_line_source** , to choose the source on output1, supported sources are:
  - LINESOURCE_OFF
  - LINE_SOURCE_EXPOSURE_ACTIVE
  - LINESOURCE_FRAME_TRIGGER_WAIT
  - LINESOURCE_TIMER_ACTIVE
  - LINESOURCE_USER_OUTPUT
  - LINESOURCE_ACQUISITION_TRIGGER_WAIT

* **user_output_line1** to switch on/off user_output on outpu1 line
For your need we added  an attribute   which select as a source for output1  "user_ouput" and set on/off (True or False) the souce.

**Comment by hayg25** [comment]
Hi Laurent, 

we tried the **user_output_line1**

```
 PyTango_WriteAttributeMethodNotFound
 Severity - ERROR
 Origin - PyTango::Attr::write
 Description - write_user_output_line1 method not found for user_output_line1
 Reason - PyTango_WriteAttributeMethodNotFound
 
```

Thx, 
Hayg

**Comment by hayg25** [comment]
Hi @laurent-claustre, 
do you have any news why the user_output_line1 failed as described in my last post (up). 
Thanks again :) 
Hayg

**Comment by laurent-claustre** [comment]
Hi, 
did you install the last conda package lima-camera-basler-tango >=1.9.1 and lima-camera-basler >=1.9.2 ?
please check your conda environment installation with:
` conda  list |grep lima-camera-basler `

**Comment by hayg25** [comment]
dear @laurent-claustre , 
indeed it works now. One additional question : 
is there a way to also access the user_output_line2 ? we do have some leds that are on that line too ...
Thanks again, 
Hayg

**Comment by laurent-claustre** [comment]
No sorry,
you could propose a code change via pull-request ?
