### ISSUE TITLE
disconnect and reconnect a CCD without using astor

### ISSUE THREAD

**Issue by PhilLAL** [esrf-bliss/Lima#113]
Hello,
some users would like to know how to do the following:
- use a CCD during one hour with device liveviewer from LimaCCDs server
- disconnect a CCD from its power supply 
- reconnect the CCD the day after
- and back again

Currently, the Devices crashed if done without following a few steps:
- EITHER kill de device before disconnecting CCD from power supply
- OR stop the device liveviewer before disconnecting CCD from power supply and THEN kill it (before or after disconnecting power supply)
- starting the device after reconnecting power supply

Our users would like to automatize these steps through python scripts. 
Do you know if there is a way to avoid passing through astor and stopping/starting again acquisition when disconnecting CCD ?

By the way, we noticed that if CCD was in acquisition when disconnected, the DS cannot be killed nor restarted through astor.

Cheers.

**Comment by laurent-claustre** [comment]
Hi Philippe, 
no way to get autoreconnect on camera with Lima. You must restart the main server LimaCCDs.

**Comment by PhilLAL** [comment]
Thank you Laurent!

**Comment by PhilLAL** [comment]
Hi @hollatz
I think it still is not possible.

**Comment by hollatz** [comment]
Hi @PhilLAL,

Thank you for the reply.
I played around with Lima but so far autoconnect does not work out of the box, at least with the Basler and Prosilica plugins.
I could also not find a way to activate autoconnect.
Executing the init method does not work either. It really needs a restart of the device server.

Cheers,
Dominik
