### ISSUE TITLE
Error building with bitshuffle

### ISSUE THREAD

**Issue by 13bscsaamjad** [esrf-bliss/Lima#114]
Hi,

I tried to build Lima with bitshuffle but failed with error: `conflicting types for ‘int64_t’` when the definition of the int64_t in `Lima/third-party/bitshuffle/src/bitshuffle_core.h:40:31` is `typedef long long           int64_t;` which is conflicting with the system definition at `/usr/include/sys/types.h:197` as `__intN_t (64, __DI__);`.

I am building on CentOS 7.6. Has anyone experience similar problem?

/Abdullah

**Comment by weninc** [comment]
GCC 4.8 (system default in CentOS7) doesn't export the __STDC_VERSION__ variable that bitshuffle relies on for detecting support for stdint.h.
Was fixed my upgrading the compiler to gcc 7 from devtoolset-7
