### ISSUE TITLE
Tiff output empty 

### ISSUE THREAD

**Issue by hayg25** [esrf-bliss/Lima#115]
Dear all, 
I am trying to save image using a script in python and when I save images using the Tiff format the images are empty while when I use Edf mode the image is not empty. 
```python
# dev_limaccd.saving_format='Edf'
dev_limaccd.saving_format='Tiff'
# dev_limaccd.saving_suffix = '.edf'   
dev_limaccd.saving_suffix = '.tiff'
```
any idea there. I tryed to save in edf format but then, I need a way to export as numpy array for example. 

Thanks

**Comment by sdebionne** [comment]
Hi Guler,
While it's not the most used format, Tiff format should work. Any chance that you could post here the script (or part of it) you are using?
Are you using the conda package that we provide or built Lima from source? Which version?
