### ISSUE TITLE
Cannot Start LimaCCDs.exe 'DLL is not found'

### ISSUE THREAD

**Issue by Saldenisov** [esrf-bliss/Lima#124]
When running 

>  **LimaCCDs 1**

I have this exception:

```
(py37_64) C:\dev\Lima>LimaCCds 1
Traceback (most recent call last):
  File "C:\Users\Elyse\miniconda3_64\envs\py37_64\Scripts\LimaCCDs-script.py", line 5, in <module>
    from Lima.Server.LimaCCDs import main
  File "C:\Users\Elyse\miniconda3_64\envs\py37_64\lib\site-packages\Lima\Server\LimaCCDs.py", line 70, in <module>
    from Lima import Core
  File "C:\Users\Elyse\miniconda3_64\envs\py37_64\lib\site-packages\Lima\Core\__init__.py", line 24, in <module>
    from limacore import *
ImportError: DLL load failed: The specified module could not be found.
```
LIMA package was installed using 

> **conda install -c conda-forge -c esrf-bcu -c tango-controls lima-camera-basler-tango**

The list of packages is this

```
(py37_64) C:\dev\Lima>conda list
# packages in environment at C:\Users\Elyse\miniconda3_64\envs\py37_64:
#
# Name                    Version                   Build  Channel
blosc                     1.21.0               h0e60522_0    conda-forge
bloscpack                 0.16.0                  py_1000    conda-forge
ca-certificates           2021.5.30            h5b45459_0    conda-forge
cmake                     3.21.3               h39d44d4_0    conda-forge
deprecated                1.2.13             pyh6c4a22f_0    conda-forge
freetype                  2.10.4               h546665d_1    conda-forge
gsl                       2.2.1                hfa6e2cd_6    conda-forge
hdf5                      1.10.6          nompi_h5268f04_1114    conda-forge
intel-openmp              2021.3.0          h57928b3_3372    conda-forge
jpeg                      9d                   h8ffe710_0    conda-forge
krb5                      1.19.2               hbae68bd_2    conda-forge
libblas                   3.9.0              11_win64_mkl    conda-forge
libcblas                  3.9.0              11_win64_mkl    conda-forge
libconfig                 1.7.2                h0e60522_1    conda-forge
libcurl                   7.79.1               h789b8ee_1    conda-forge
libjpeg-turbo             2.1.0                h8ffe710_0    conda-forge
liblapack                 3.9.0              11_win64_mkl    conda-forge
libpng                    1.6.37               h1d00b33_2    conda-forge
libssh2                   1.10.0               h680486a_2    conda-forge
libtiff                   4.0.10            h016b793_1002    conda-forge
lima-camera-basler        1.9.3            py37h74a9793_0    esrf-bcu
lima-camera-basler-tango  1.9.4                         0    esrf-bcu
lima-core                 1.9.8            py37h2e52968_0    esrf-bcu
lima-tango-server         1.9.13                     py_0    esrf-bcu
lz4-c                     1.8.2                he025d50_0    conda-forge
mkl                       2021.3.0           hb70f87d_564    conda-forge
numpy                     1.21.2           py37h940b05c_0    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openssl                   1.1.1l               h8ffe710_0    conda-forge
pillow                    8.1.0            py37hedcef43_1    conda-forge
pip                       21.2.4             pyhd8ed1ab_0    conda-forge
processlib                1.7.5            py37h926398c_0    esrf-bcu
pylon5-sdk                5.1.0                         0    esrf-bcu
pylon6-sdk                6.2.0                         0    esrf-bcu
pymemcache                3.5.0              pyhd8ed1ab_0    conda-forge
pytango                   9.3.1            py37h39e3cac_1    tango-controls
python                    3.7.10          h7840368_101_cpython    conda-forge
python-blosc              1.10.2           py37hd6fb530_1    conda-forge
python_abi                3.7                     2_cp37m    conda-forge
pyturbojpeg               1.6.1              pyhec5db9e_0    conda-forge
setuptools                58.0.4           py37h03978a9_2    conda-forge
sip                       4.19.8          py37h6538335_1000    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sqlite                    3.36.0               h8ffe710_2    conda-forge
tbb                       2021.3.0             h2d74725_0    conda-forge
tk                        8.6.11               h8ffe710_1    conda-forge
ucrt                      10.0.20348.0         h57928b3_0    conda-forge
vc                        14.2                 hb210afc_5    conda-forge
vs2015_runtime            14.29.30037          h902a5da_5    conda-forge
wheel                     0.37.0             pyhd8ed1ab_1    conda-forge
wrapt                     1.12.1           py37hcc03f2d_3    conda-forge
xz                        5.2.5                h62dcd97_1    conda-forge
zlib                      1.2.11            h62dcd97_1010    conda-forge
zstd                      1.3.3                    vc14_1    conda-forge
```

**Comment by sdebionne** [comment]
Hi @Saldenisov,

I could NOT reproduce the issue with:

```
$ conda create -n test_basler
$ conda activate test_basler
$ conda install -c conda-forge -c esrf-bcu -c tango-controls \
    lima-camera-basler-tango

$ python
>>> from limacore import *
>>>

$ conda list lima

# packages in environment at C:\Miniconda3\envs\test_basler:
#
# Name                    Version                   Build  Channel
lima-camera-basler        1.9.4            py37h74a9793_0    esrf-bcu
lima-camera-basler-tango  1.9.4                         0    esrf-bcu
lima-core                 1.9.10           py37h74a9793_0    esrf-bcu
lima-tango-server         1.9.13                     py_0    esrf-bcu
```

Any chance that you forgot to activate the conda environment you installed the tango DS in?

**Comment by laurent-claustre** [comment]
Hi,
strange you get both installed the pylon5-sdk and pylon6-sdk? did you force installation of the version 6?
This lima camera plugin version 1.9.4 for basler is only working with pylon5. Please, uninstall pylon6-sdk and try again.

**Comment by sdebionne** [comment]
From the backtrace 
```
File "C:\Users\Elyse\miniconda3_64\envs\py37_64\lib\site-packages\Lima\Core\__init__.py", line 24, in <module>
    from limacore import *
ImportError: DLL load failed: The specified module could not be found.
```
it looks like it's the lima core (python bingind) that is not found...

**Comment by Saldenisov** [comment]
@sdebionne It is clear that limacore is guilty, but why?

`# packages in environment at C:\Users\elysium\.conda\envs\py37_64:
#
# Name                    Version                   Build  Channel
lima-camera-basler        1.9.3            py37h74a9793_0    esrf-bcu
lima-camera-basler-tango  1.9.4                         0    esrf-bcu
lima-core                 1.9.8            py37h2e52968_0    esrf-bcu
lima-tango-server         1.9.13                     py_0    esrf-bcu`

**Comment by Saldenisov** [comment]
Hi @laurent-claustre,

Now I have only:
`pylon5-sdk                5.1.0                         0    esrf-bcu`

But the error is still there:
Traceback (most recent call last):
  File "C:\Users\elysium\.conda\envs\py37_64\Scripts\LimaCCDs-script.py", line 5, in <module>
    from Lima.Server.LimaCCDs import main
  File "C:\Users\elysium\.conda\envs\py37_64\lib\site-packages\Lima\Server\LimaCCDs.py", line 70, in <module>
    from Lima import Core
  File "C:\Users\elysium\.conda\envs\py37_64\lib\site-packages\Lima\Core\__init__.py", line 24, in <module>
    from limacore import *
ImportError: DLL load failed: The specified module could not be found.

**Comment by sdebionne** [comment]
- Could you print `set PATH` when the env is activated?
 - Check that you have the `liblimacore` dll in `C:\Users\elysium.conda\envs\py37_64\Library\bin` ?
 - Check that  you have `limacore.pyd` dll in `C:\Users\elysium.conda\envs\py37_64\Lib\site-packages` ?

Do you have experience with [dependency walker](http://dependencywalker.com/)?

**Comment by Saldenisov** [comment]
@sdebionne the PATH is this for my environment
`PATH=C:\Users\Elyse\anaconda3\envs\py37_64;
C:\Users\Elyse\anaconda3\envs\py37_64\Library\mingw-w64\bin;
C:\Users\Elyse\anaconda3\envs\py37_64\Library\usr\bin;
C:\Users\Elyse\anaconda3\envs\py37_64\Library\bin;
C:\Users\Elyse\anaconda3\envs\py37_64\Scripts;
C:\Users\Elyse\anaconda3\envs\py37_64\bin;
C:\Users\Elyse\anaconda3\condabin;
C:\Program Files (x86)\Common Files\Oracle\Java\javapath;
C:\Program Files\National Instruments\Shared\OpenVINO;
C:\WINDOWS\system32;
C:\WINDOWS;
C:\WINDOWS\System32\Wbem;
C:\WINDOWS\System32\WindowsPowerShell\v1.0;
C:\WINDOWS\System32\OpenSSH;
C:\Program Files (x86)\IVI Foundation\VISA\WinNT\Bin;
C:\Program Files\IVI Foundation\VISA\Win64\Bin;
C:\Program Files (x86)\IVI Foundation\VISA\WinNT\Bin;
C:\Program Files (x86)\National Instruments\Shared\LabVIEW CLI;
C:\dev\tango_root\tango\bin;
C:\Program Files\MySQL\MySQL Server 8.0\bin;
C:\Program Files\MySQL\MySQL Server 5.7\bin;
C:\Program Files\Git\cmd;
C:\Program Files\Inkscape\bin;
C:\Program Files\MySQL\MySQL Shell 8.0\bin;
C:\Users\Elyse\AppData\Local\Microsoft\WindowsApps;
C:\Program Files\JetBrains\PyCharm 2021.2.2\bin;
.;
C:\Users\Elyse\AppData\Local\Programs\MiKTeX\miktex\bin\x64;
C:\Program Files\JetBrains\PyCharm Community Edition 2021.2.2\bin;
.;
C:\Users\Elyse\anaconda3\envs\py37_64\Lib\site-packages`

**Comment by Saldenisov** [comment]
@sdebionne Here what dependency scanner gives [LimaCCDs.dwi](https://we.tl/t-whIjHFOMjv).

Thanks for help

**Comment by sdebionne** [comment]
DW give no error for `LimaCCDs.exe` but that's because it's only an entrypoint for the Python script...

BTW you need to start Dependency Walker from the Anaconda prompt (with the env activated) to get proper the proper `PATH` set.
