### ISSUE TITLE
git submodule update --init --recursive after cloning fails

### ISSUE THREAD

**Issue by birkenfeld** [esrf-bliss/Lima#126]
because 
```
fatal: No url found for submodule path 'camera/template' in .gitmodules
```
With `git clone --recursive` it works, but this (`clone` followed by `submodule update`) is a standard way to initialize submodules properly and should not fail.

**Comment by laurent-claustre** [comment]
Hi
sorry for these few issues, there are related to some missing update of submodule references in the main repository.
I will fix that this week.

**Comment by laurent-claustre** [comment]
If you want to run an supported camera, you can download the Conda packages, then no need to compile anything.

**Comment by birkenfeld** [comment]
Thanks! Conda won't work for us, we are building RPMs for our OS/Python for all custom software.

**Comment by laurent-claustre** [comment]
With Conda, you don't need to have any OS dependencies.
could you tell me more about your Lima usage? which cameras are you using?

**Comment by birkenfeld** [comment]
We're using only Andor, currently. We don't use Conda at all, and want to do central rollout of packages using our own RPM package repository. This is why we build all necessary software from source.

**Comment by birkenfeld** [comment]
This specific problem seems fixed now. #127 still persists with iris camera.
