### ISSUE TITLE
Lima-camera-ximea submodule requires authentication for cloning

### ISSUE THREAD

**Issue by birkenfeld** [esrf-bliss/Lima#127]
```
Cloning into '/home/x/Lima/camera/ximea'...
Username for 'https://github.com': 
Password for 'https://github.com': 
remote: Repository not found.
fatal: Authentication failed for 'https://github.com/esrf-bliss/Lima-camera-ximea/'
fatal: clone of 'https://github.com/esrf-bliss/Lima-camera-ximea' into submodule path '/home/gbrandl/Lima/camera/ximea' failed
```

(with pressing "enter" for username/password)

**Comment by sdebionne** [comment]
Hi @birkenfeld, Lima-camera-ximea is now properly mirrored to github, could you try again?

**Comment by sdebionne** [comment]
This repository is currently public. I think you should access it rather with `https://`, if you use the git protocol then you need to load a private key, no?

**Comment by birkenfeld** [comment]
I agree that `https://` should be used. However, It's not me cloning via `git://`, it's the submodule specification in the `.gitmodules` file, [here](https://github.com/esrf-bliss/Lima/blob/master/.gitmodules#L3) and [here](https://github.com/esrf-bliss/Lima/blob/master/.gitmodules#L105) and [here](https://github.com/esrf-bliss/Lima/blob/master/.gitmodules#L118).

(As far as I understand, `git://` was never used for cloning with private keys, that is `ssh://`. It is an alternate read-only protocol, which GitHub stopped supporting recently.)

**Comment by sdebionne** [comment]
You are right, the `.gitmodules` file seems incorrect.  We have always try to use relative path in `.gitmodules` so that one can checkout via `https://` or `ssh://` indifferently. @laurent-claustre We should fix that ASAP.

**Comment by birkenfeld** [comment]
`lima-camera-ximea` is now ok, but `lima-camera-iris` requires authentication.

**Comment by laurent-claustre** [comment]
fixed
