### ISSUE TITLE
PROBLEM INSTALLING LiMA

### ISSUE THREAD

**Issue by leito92** [esrf-bliss/Lima#129]
Hello,
I can't install the LiMA on Linux from the source.  I need help!
Best,

**Comment by laurent-claustre** [comment]
Hi again,
could you tell us more?

**Comment by leito92** [comment]
[detector_tango_install.txt](https://github.com/esrf-bliss/Lima/files/7899730/detector_tango_install.txt)
[detector_tango_error.txt](https://github.com/esrf-bliss/Lima/files/7900113/detector_tango_error.txt)

I attached the steps on what I did.
When I run the script, it stops in the middle of execution and tells me: "Problem building/installing Lima: CMake could not build Lima".
I also attached the error file.

**Comment by laurent-claustre** [comment]
Hi,
it seems theres is mismatch between the gcc pthread and your native CC pthreads (with a **s** a the end).
On which platform and with which compiler are you building ?

**Comment by sdebionne** [comment]
And wich version of CMake? It's strange that the `FindThreads` module fails. Here is the [doc](https://cmake.org/cmake/help/v3.18/module/FindThreads.html). Maybe you need to set `THREADS_PREFER_PTHREAD_FLAG` on your platform? Or are you cross compiling?

**Comment by leito92** [comment]
I am working with docker. The platform is Debian and the compiler is gcc.
The version of CMake is 3.13.4 but I do not understand the question: "are you cross compiling?".

**Comment by laurent-claustre** [comment]
if you are looking for the QHYccd camera support in LIMA project, you can stop now, there is not code available for this type of camera, since the main developer (tester) did never finish to test. And we do have such detector at ESRF.
Sorry for the inconvenience.

**Comment by leito92** [comment]
So, how can I install LiMA for QHYCCD camera?

**Comment by leito92** [comment]
Yes, I want to do.
How can I install the LiMA library to use it in my code for QHYCCD?

**Comment by sdebionne** [comment]
Maybe that [documentation](https://lima1.readthedocs.io/en/latest/plugin/index.html#setting-up-a-development-environment) would help to setup a dev env.

**Comment by leito92** [comment]
only by conda can I install lima-core?

**Comment by laurent-claustre** [comment]
Hi,
yes, this is the easiest way for you to compile a new camera plugin. Create an empty conda env., then install the lima-camera-simulator-tango package, you then get all you need, lima-core, processlib, other third-party packages to compile your code.

**Comment by leito92** [comment]
Hi,
I am working on a Raspberry Pi 3 B+. I can not install lima-core with conda. Is there no other way to have lima-core for python?

**Comment by sdebionne** [comment]
Using Conda to setup a dev env is only a suggestion, you can of course build from source on your Raspberry Pi. All you need is a C++ compiler and CMake recent enough and to install all 3rd party dependencies that you want to support in your build (e.g. HDF5). If you have all that installed on your target system, then building Lima should be relatively simple:

```
cmake -Bbuild -H. -DLIMA_ENABLE_PYTHON=ON
cmake --build build --target install
```

You can add more options to the configure step (the first command line), e.g.   `-DLIMA_ENABLE_HDF5=ON`.

**Comment by leito92** [comment]
hello again.. what compiler version should I have?

**Comment by sdebionne** [comment]
To be on the safe side,  I would say `g++ > 7.2`.

**Comment by leito92** [comment]
Hi,
I keep having problems installing LImA.
I did: "./install.sh --install-prefix=${HOME} tests".
Where can I locate "Lima.Core" that it is used in the import?

**Comment by sdebionne** [comment]
It should be installed in you python dist packages folder:

```py
python -c 'import site; print(site.getsitepackages())'
``` 

The  C++ libraries should be in `${HOME}/lib`, headers in `${HOME}/include` as usual on Linux.
