### ISSUE TITLE
device naming for Lima plugin

### ISSUE THREAD

**Issue by PhilLAL** [esrf-bliss/Lima#131]
Hi,
when using `A/B/C` for a LimaCCDs used with a Basler, we manually create devices for LimaCCDs and Basler devices.

Then, if we use plugins, other devices are created:
- A/liveviewer/C
- A/backgroundsubstraction/C
- A/flatfield/C
- A/limatacoccds/C
- A/ roi2spectrum/C
- A/roicounter/C
- A/bpm/C
- A/peakfinder/C
- A/mask/C
- A/ctvideo/C
- A/ctaccumulation/C
- A/ctimage/C
- A/ctevent/C
- A/ctbuffer/C
- A/ctconfig/C
- A/ctshutter/C
- A/ctsaving/C
- A/ctacquisition/C
- A/ctcontrol/C
- A/memcached/C
- A/roicollection/C

For example, if bla/truc/ccd.01 exists as well as bla/machin/ccd.01, then both will create bla/liveviewer/ccd.01, am I right?

Then I understand Lima assumes C will be unique among all A/B, am I right?

Since naming depends on accelerators, it is possible this renaming occurs issues?
How to do this?

Thank you

**Comment by PhilLAL** [comment]
Thanks @laurent-claustre, but devices will not have dependencies issues if I rename them how I want?
They all depends only on LimaCCDs and Basler?

**Comment by laurent-claustre** [comment]
No, you can rename the devices as you want, only the code behind is sharing the lima python objects coming from the library. You can make a test and you will see this will work like a charm

**Comment by PhilLAL** [comment]
Thank you very much, again :)
