### ISSUE TITLE
Differences between the camera plugin and camera DS

### ISSUE THREAD

**Issue by ijamime** [esrf-bliss/Lima#132]
Hi,

I was wondering about the differences between the canera device server and the camera plugin inside LImA architecture, and its relations with LimaCCDs.

Is it safe to consider that the plugin is part of the DS and runs inside of it? Or is the DS contacts the plugin which run separately?

In both cases, is the DS part of LimaCCDs (due to the fact that when creating and launching the main DS, a property is added to specify the detector model) and what we develop inside the tango folder is merely a script to connect the plugin to LimaCCDs or is the DS is separated from the LimaCCDs and in that case is it recognised by TANGO?

I know that all of this doesn't affect the development, but just wanted to understand what is considered what.

**Comment by laurent-claustre** [comment]
Hi,
the LimaCCDs server is a single process, so all the tango "devices" created are runing inside this single process.
When you start the device server you can check on your computer that only one process is running, on linux you will see several threads since Tango is mutlithreaded.

**Comment by ijamime** [comment]
In that case what is the purpose of the DS that is developped inside the tango folder? Is it to connect the camera plugin to the LimaCCDs?

Also what about the others plugins such as LimaViewer or BPM? Are those also part of LimaCCDs?

**Comment by sdebionne** [comment]
> In that case what is the purpose of the DS that is developped inside the tango folder? Is it to connect the camera plugin to the LimaCCDs?

Correct, the python code in the plugin tango folder introduces the "camera specific" part of the DS, if any.
