### ISSUE TITLE
Threads in Camera class

### ISSUE THREAD

**Issue by ijamime** [esrf-bliss/Lima#133]
Hi,

I'm currently working on a new camera plugin and am using some of the other plugins as references. Only that I've found issues understanding some of the coding done in the Camera class.

For instance, some plugins use threads and others don't (Prosilica for example). And for those that use threads, I've found two methods:
 1. Creating a `CameraThread` private class that inherit from CmdThread (used by Simulator and Lambda).
 2. Creating an `_AcqThread` private class that inherits from Thread (used by Basler).

Is there any "correct" way of doing things?

**Comment by laurent-claustre** [comment]
sometimes the camera SDK provides high level functions where threading is embedded like for Prosilica, for others we must implement the threading to acquire as fast as possible the coming frames. 
Lima provides a thread tool-box called CmdThread you can use or you can code your own threading mechanism using system thread (e.g pthread for linux). Up to you, CmdThread is easy to use and Lambda plugin is a code example.
