### ISSUE TITLE
list of conda packages available

### ISSUE THREAD

**Issue by PhilLAL** [esrf-bliss/Lima#134]
Hello,
linked to this [PhotonicScience](https://github.com/esrf-bliss/Lima-camera-photonicscience/issues/1) ticket, is there somewhere a list of all packages and where to find them (by default esrf-bcu channel I suppose) ?
Regards

**Comment by sdebionne** [comment]
> by default `esrf-bcu` channel I suppose

Correct! Every packages that we have in a stable state should be on [Anaconda](https://anaconda.org/esrf-bcu/repo), just `mamba search 'lima-camera-*>=1.9' -c esrf-bcu` to get the current list.

**Comment by PhilLAL** [comment]
Thank you @sebionne and @laurent-claustre :)

**Comment by PhilLAL** [comment]
Hi, perhaps there is somewhere in the doc where this precious information could be put? It would allow to get the packages information even when the list is not up-to-date?
