### ISSUE TITLE
Lima install (mamba package)

### ISSUE THREAD

**Issue by PhilLAL** [esrf-bliss/Lima#140]
Hello,
following installation instructions on page https://lima1.readthedocs.io/en/latest/build_install.html, I encountered an error while installing mamba. 
It is not major issue since install can be done through conda without mamba for the users which know mamba/conda (a bit of information will be useful for others).

Here is the message:
```$ conda install mamba
Collecting package metadata (current_repodata.json): done
Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - mamba

Current channels:

  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

From https://anaconda.org/conda-forge it seems the correct instruction should be `conda install  -c conda-forge mamba`.

**Comment by laurent-claustre** [comment]
Hi Phil,
yes, you're right, there is missing option "-c conda-forge".
In general we should always set conda-forge the default and top channel in a new environment.
I will correct the documentation.

**Comment by PhilLAL** [comment]
Just a reminder since the doc still indicate `conda install mamba`

**Comment by laurent-claustre** [comment]
Hi Philippe,
done, it will be available with the next release of lima.

**Comment by physics-dev** [comment]
I was stuck in this situation for about 3 hours.
Thank you, everyone!
