### ISSUE TITLE
"‘ptr’ was not declared in this scope" when building

### ISSUE THREAD

**Issue by PhilLAL** [esrf-bliss/Lima#37]
Hi,
while building with make, I got this message:

```
g++ -I../include -I../../hardware/include -I../../third-party/Processlib/core/include -Wall -pthread -fPIC -g -DHAS_INOTIFY -DWITH_CONFIG -I../../third-party/libconfig/lib   -c -MD -I../include -I../../hardware/include -I../../third-party/Processlib/core/include -Wall -pthread -fPIC -g -DHAS_INOTIFY -DWITH_CONFIG -I../../third-party/libconfig/lib -o MemUtils.o MemUtils.cpp
MemUtils.cpp: In constructor ‘lima::MemBuffer::MemBuffer(int)’:
MemUtils.cpp:133: error: ‘ptr’ was not declared in this scope
```

The problem is into common/src/MemUtils.cpp at line 118:

`char* ptr = (char*)m_ptr;`

which is into #ifdef __SSE2__ instead of outside.
Moving it from line 118 to line 117 seems to solve this issue.

**Comment by laurent-claustre** [comment]
Ok I "cherry-picked"  the commit from core-1.6. I send a general message to lima@esrf.fr for the new release and about the documentation udpates.
Thanks a lot for your contributions.

Laurent
