### ISSUE TITLE
Request for Feature: could the LimaTacoCCDs device know its parent device ?

### ISSUE THREAD

**Issue by fatboy92** [esrf-bliss/Lima#41]
I am working with a plugin, which in the manner of Lima creates its own device. 

The device names of the lima main device (LimaCCDs, why there is an "s" at the end is unclear to me) are related only in the tango device name's first part and the last.

I can ask the main device for the device name of a plugin created device name (getPluginDeviceNameFromType).
However, the inverse is not possible (yet). 

To be able to derive the main servers tango name from the LimaTacoCCDs device (I am working in spec) I am cutting strings, which seems to me  a rather unsafe way of obtaining the main server's name. 

Would it be possible to add a taco command to the taco part of the lima server, to return the main lima devices name ? 
Many thanks
Holger

**Comment by laurent-claustre** [comment]
Sorrry, but we will not do that.

Cheers.
Laurent
