### ISSUE TITLE
Change image width and image height in Lima DS (basler camera)

### ISSUE THREAD

**Issue by izadworny** [esrf-bliss/Lima#49]
In PylonViewerApp which is dedicated to Basler camera there is possibility to set image width and image height. How can I do that in Lima device server? I'd like to resize it to 640x480.

**Comment by sebastien-petitdemange** [comment]
Are you taking about image ROI (Region Of Interest) or Binning or something else?

**Comment by izadworny** [comment]
I need to reduce image size acquired by DS. In Pylon it is AOI controls -> width, height.

**Comment by sebastien-petitdemange** [comment]
You have the equivalent with **image_roi** attribute in LimaCCDs server.

**Comment by izadworny** [comment]
Thank you for your help. I have checked it and found that image_roi works exactly like AOI in Pylon. It gives a part of big image. I didn't know about it earlier.
Unfortunately this is not what I need. Is it possible to get full image but in lower resolution?

**Comment by sebastien-petitdemange** [comment]
You probably want to use the binning.
In the server you'll find the attribute **image_bin**.

i.e: image_bin = 2,2 => width/2 and height/2.
