### ISSUE TITLE
patching attribute names causes SEG FAULT

### ISSUE THREAD

**Issue by jkotan** [esrf-bliss/Lima#50]
I've just wanted to start LimaCCDs in Similator mode on my box but when I try to do it
I get SEG FAULT, i.e.

    jkotan@haso228k:~/sources/Lima/applications/tango/python$ git checkout master
    Switched to branch 'master'
    Your branch is up-to-date with 'origin/master'.
    jkotan@haso228k:~/sources/Lima/applications/tango/python$ ./LimaCCDs.py TEST
    ctcontrol.accumulation() = <EnvHelper.CtAccumulation object at 0x7f2c6b050390>
    ctcontrol.acquisition() = <EnvHelper.CtAcquisition object at 0x7f2c6b05fdd0>
    ctcontrol.shutter() = <EnvHelper.CtShutter object at 0x7f2c642a9410>
    Segmentation fault

I can fix the issue by the following patch:

    diff --git a/EnvHelper.py b/EnvHelper.py
    index 03f3b2d..f76f29f 100644
    --- a/EnvHelper.py
    +++ b/EnvHelper.py
    @@ -393,12 +393,12 @@ def to_tango_object(ct, name_id):
					     self.__dict__["__name"])
		 return PyTango.client._Device, (name,)

    -    for name, value in patched_members.items():
    -        setattr(klass, name, property(*value))
    -
	 klass.__name__ = ct_klass_name
	 ct_tango_map[ct_klass] = klass
    -    return klass(ct, name_id)
    +    kl = klass(ct, name_id)
    +    for name, value in patched_members.items():
    +        setattr(kl, name, property(*value))
    +    return kl

     def create_tango_objects(ct_control, name_template):

It looks like attributes are set before class instantiation which maybe risky
and cause in my case SEG FAULT.

Bests,
Jan

**Comment by sebastien-petitdemange** [comment]
Could you create a PR or send us a git patch.

Thanks in advance

**Comment by jkotan** [comment]
Done at:

https://github.com/esrf-bliss/Lima-tango-python/pull/6/files
