### ISSUE TITLE
Import Lima under conda and windows 8

### ISSUE THREAD

**Issue by labinphyni2017** [esrf-bliss/Lima#55]
Hi, I'm trying to install Lima to interface a Basler camera with Python. Python is installed with miniconda on a PC under Windows 8.
When i run the install.bat, it returns that it can found the path specified...
Can you help me ? Is there a simpler way to install this library via conda, or git function ?

Romain

**Comment by laurent-claustre** [comment]
Hi Romain,
could you send us some traces returned by install.bat, please?
Cheers
Laurent

**Comment by labinphyni2017** [comment]
Thank you for your response.
Here what it prompt when running the install.inc (it also opens the file "python_path") :

![image](https://user-images.githubusercontent.com/30687463/29082183-0d4e2866-7c65-11e7-914e-97cbcc213aa7.png)

I tried to install it on anaconda prompt, under my conda environnement, unsuccesfully : 
![image](https://user-images.githubusercontent.com/30687463/29082429-c52fde34-7c65-11e7-9355-e2d95210fb83.png)
 
Romain

**Comment by laurent-claustre** [comment]
Hi Romain,
Lima is  written in C++ provides a python binding as well. Please read the doc at lima.blissgarden.org for installation.
You need Visual C++ 2008 Express 
install.bat is complaining about missing tool like vcvarscall.bat provided by V C++ Express for setting environment. The script needs msbuild.exe the microsoft compiler, again provided with the VC++ suite.

Cheers.
Laurent

**Comment by labinphyni2017** [comment]
Hi Laurent,
Ok my mistake. But this is not going well after the installation of Visual C++ 2008 Express :

![image](https://user-images.githubusercontent.com/30687463/29111256-cc6f9ca0-7ce9-11e7-9dc1-de2e33ee4b83.png)

**Comment by laurent-claustre** [comment]
Hi Roman,
did you install the third-party Processlib??
git init third-party/Processlib
git update third-party/Processlib

Cheers

**Comment by labinphyni2017** [comment]
Hi,
I don't. This wasn't specified in http://lima.blissgarden.org/install_windows.html#getit
Have you a more recent or completed guide for the installation ?

Either I run these commands in conda or cmd, I get the same results on the left of the screen shot.
If i tried to run the install.inc of Lima, it return the cmd on the right and open the python_path file :
![image](https://user-images.githubusercontent.com/30687463/29170129-736ec3e4-7dd7-11e7-9a2f-b749f8f24176.png)

**Comment by laurent-claustre** [comment]
sorry Romain, my last instruction were wrong, missing submodule keywork in git command and forget about make, but use of course install.bat.  install.inc is not suitable for windows so fo not try anything with it .

Under your Lima repository run:
git submodule init third-party/Processlib
git submodule update

install.bat

**Comment by labinphyni2017** [comment]
Here's the news.
After provide the Processlib and camera Basler files in the lima directory, I needed to install Qt and SIP.
I install Qt version 5.6.2 under conda ; with conda install Qt
Then I downloaded the SIP source.

![image](https://user-images.githubusercontent.com/30687463/29207392-4cbb203a-7e86-11e7-8e1b-c42823f4193e.png)

I can call my conda environnement from the windows cmd by "activate P3" (P3 being the environnement name)
I run in the SIP directory : python configure.py   
This look fine.
I indicate the path to VS ; then run nmake
But I got the Fatal Error U1077 ...
Maybe the problem is the compatiblity between Qt and MVS 2008.
I continue search a solution but any help is welcome

**Comment by laurent-claustre** [comment]
Hi Romain,
try with an older version of SIP, 4.18 or even 4.16. 4.19 seems to generate a Makefile with compiler option -FS no recognize by VC++ 9.0.

**Comment by labinphyni2017** [comment]
Hi Laurent,
Finally, SIP seems to be built (left cmd) but running the install.bat of lima get me the cmd on the right plus open the python path file...

![image](https://user-images.githubusercontent.com/30687463/29219271-dfbe9dc2-7eb7-11e7-97f7-94ec3fc24d5d.png)

**Comment by laurent-claustre** [comment]
Hi Romain,
according to the error messages you have on the right window, you have some permission issues??
Any command cannot write files into your installation directory under Lima-master/.....

Laurent

**Comment by labinphyni2017** [comment]
Hi Laurent,
When running install.bat in admin user i got this cmd which rapidly close itself.

![image](https://user-images.githubusercontent.com/30687463/29554858-fc8b6374-8720-11e7-935c-c843073f65c0.png)

Maybe the path isn't correct (C:\Program Files\Basler\pylon 5\Lima-pylon5) ? 

Romain
