### ISSUE TITLE
processlib_tmp.sip:333:5: error: ‘import_array’ was not declared in this scope

### ISSUE THREAD

**Issue by JiangXL** [esrf-bliss/Lima#56]
Lima failed to be installed in Archlinux (3.15lts Linux Kernel) with numpy(1.13).
All is well before fllowing error:

     make -C sip -j3
 
     ......

     processlib_tmp.sip:333:5: error: ‘import_array’ was not declared in this scope

     import_array();

     ^~~~~~~~~~~~
     processlib_tmp.sip:334:3: warning: no return statement in function returning non-void [-
    Wreturn-type]
     }
     ^
     processlib_tmp.sip: In function ‘PyObject* varget_Data_buffer(void*, PyObject*, PyObject*)’:
     processlib_tmp.sip:324:32: error: ‘_ProcessLibNumpyArray’ was not declared in this scope
      #define PY_ARRAY_UNIQUE_SYMBOL _ProcessLibNumpyArray 
                                    ^ 

What kind of error it is? Maybe is numpy version be wrong?
Any help is **welcome**!

**Comment by laurent-claustre** [comment]
Dear you,
On which branch are your working? stable one (as discribed in the doc) is core-1.7
- can you send us the processlib_tmp.sip file?
- you sip version (sip -V)?

Cheers
Laurent

**Comment by JiangXL** [comment]
Thank to you reply! 
+ The branch is latest release core-1.7.2, which I clone from GitHub.
+ sip 4.19.3-1 is installed from Archlinux Source.
+ processlib_tmp.sip is on `/Lima/third-party/Processlib/sip/ `. 
[processlib_tmp.zip](https://github.com/esrf-bliss/Lima/files/1208922/processlib_tmp.zip)

**Comment by laurent-claustre** [comment]
Hi Jiang,
We never tried compiling Lima on numpy 1.13, but it should work.
import_array() is supposed to be defined from a numpy include file __multiarray_api.h. In the processlib.sip
file we include numpy/arrayobject.h which includes ndarrayobject.h which includes __multiarray_api.h .
Could you send me the third-party/Processlib/sip/Makefile file? 
I will check your python dist-packages path for numpy include directory.

Cheers.
Laurent

**Comment by JiangXL** [comment]
Hi Laurent,
I guess that some API of numpy has changed since [numpy 1.13](https://docs.scipy.org/doc/numpy/release.html).
But I am not similar with Lima and numpy, I can't make a conclusion.

[Makefile.zip](https://github.com/esrf-bliss/Lima/files/1210939/Makefile.zip)

Cheers.
Jiang

**Comment by laurent-claustre** [comment]
Hi Jiang,
could you try using python2,7 instead of 3.5?
make your default python script running python2.7 instead of python3.5.
Then run:
make clean
make config
make

Cheers.
Laurent

**Comment by JiangXL** [comment]
Hi Laurent,
Finally, Lima is compiled successfully using python2.7. However, it will be excited if Lima can work with python3. 

Thinks!

Cheers.
Jiang
