### ISSUE TITLE
cmake branch: Issue when installing on linux distro using lib64 dirs

### ISSUE THREAD

**Issue by HighwayStar** [esrf-bliss/Lima#65]
Trying new cmake branch and it builds fine overall, but has issue installing shared libs. openSUSE distro uses lib64 dirs for 64-bit shared libs, but current cmake code always install it to lib. It can be fixed by using simple code like described here https://cmake.org/pipermail/cmake/2013-July/055374.html

```
get_property(LIB64 GLOBAL PROPERTY FIND_LIBRARY_USE_LIB64_PATHS)

if ("${LIB64}" STREQUAL "TRUE")
    set(LIBSUFFIX 64)
else()
    set(LIBSUFFIX "")
endif()

set(INSTALL_LIB_DIR     lib${LIBSUFFIX} CACHE PATH "Installation
directory for libraries")
mark_as_advanced(INSTALL_LIB_DIR)
```

and using ${INSTALL_LIB_DIR} here https://github.com/esrf-bliss/Lima/blob/cmake/CMakeLists.txt#L484  and in other CMakeLists.txt files. 

Same issue with detecting python site-packages it should use both /usr/__lib__/python2.7/site-packages/ /usr/__lib64__/python2.7/site-packages/ but now only uses lib here.

**Comment by laurent-claustre** [comment]
Hi,
Since cmake 3.0,  one can use the GNUInstallDirs module: 
https://cmake.org/cmake/help/v3.0/module/GNUInstallDirs.html
Could you make a try like this, we only have debian distro  at ESRF for which default install dir is /usr/local:

if(WIN32)
    install(TARGETS limacore
            DESTINATION lib
            PUBLIC_HEADER DESTINATION include)
else()
    include(GNUInstallDirs)
    install(TARGETS limacore
            LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
            PUBLIC_HEADER DESTINATION ${CMAKE_INSTALL_INCLUDEDIR})
endif()

**Comment by HighwayStar** [comment]
Yes, this way works good too.

**Comment by HighwayStar** [comment]
Proper python site-packages dir can be found using ```get_python_lib(True)``` instead of ```get_python_lib()``` https://docs.python.org/2/distutils/apiref.html#distutils.sysconfig.get_python_lib

**Comment by laurent-claustre** [comment]
Ok, I will merge the changes with cmake branch this week.

**Comment by HighwayStar** [comment]
This code block also needed on openSUSE Linux https://github.com/esrf-bliss/Lima/blob/cmake/CMakeLists.txt#L156
