### ISSUE TITLE
Expose raw statistics

### ISSUE THREAD

**Issue by hardion** [esrf-bliss/Lima#69]
At this moment only processed statistic are reported by lima saving.
By exposing the raw data we can get access to the timestamp of each event. This would lead to have a better diagnostic of the streaming and recording.

**Comment by hardion** [comment]
I can write a PR but you can maybe enlight me on the way to go. 
The raw data are given by the  CtSaving::getRawStatistic but should we report via the StatisticsType or standard type?
Some advice are welcome.

**Comment by sebastien-petitdemange** [comment]
Hi @hardion, For the c++ interface, it's better to report it via StatisticsType but for the Python API, I think it will be nicer to expose statistics with standard type like **Structured array from numpy** (https://docs.scipy.org/doc/numpy/user/basics.rec.html).
To do that you have to manually code in sip the method (I can help you with that).
If you have other idea, feel free to propose.
