### ISSUE TITLE
Lima does not start for Basler: ValueError: Attempted relative import in non package

### ISSUE THREAD

**Issue by PhilLAL** [esrf-bliss/Lima#77]
Hi,
after installing Lima for specific basler camera (`/home/ccthomx/depots/Lima-basler`) following https://lima-doc.readthedocs.io/en/latest/getit.html#for-a-specific-camera instructions, I added the DS to $TANGO_HOST and I can see the result into jive, it seems OK.
According to https://lima-doc.readthedocs.io/en/latest/build_install.html#environment-setup I configured env variable:
```
$ echo $LD_LIBRARY_PATH
/opt/pylon5:/usr/lib/:/home/ccthomx/Lima-install/Lima/lib
$ echo $PYTHONPATH
/home/ccthomx/taurus:/home/ccthomx/Lima-install/python
```
FYI:
```
$ echo $PATH
/home/ccthomx/.local/bin:/usr/local/bin:/usr/bin:/bin:
```

Then, I launched `/home/cc/Lima-install/python/Lima/Server/LimaCCDs.py lima1` (and I tested also `python /home/ccthomx/depots/Lima-basler/applications/tango/python/LimaCCDs.py lima1`).
I get similar outputs:
```
Traceback (most recent call last):
  File "/home/cc/Lima-install/python/Lima/Server/LimaCCDs.py", line 64, in <module>
    from .EnvHelper import get_sub_devices
ValueError: Attempted relative import in non-package
```
It seems there is some environment variable error, am I right?
If so, how could I solve this?

Regards.

**Comment by PhilLAL** [comment]
I changed the title to make it more clear.

**Comment by sdebionne** [comment]
I don't think that is is related to environment variable.
Could you check that you have `EnvHelper.py` along with `LimaCCDs.py`?
I assume that `home/ccthomx/Lima-install/Lima/` is your install prefix, right? Could you try to run `home/ccthomx/Lima-install/Lima/bin/LimaCCDs lima1` instead of running the python script directly?
Did you install the tango server with CMake (or the install.sh script) or just copied the files from repo?

**Comment by sdebionne** [comment]
Phil,
Your install command is fine. Running `Lima-install/bin/LimaCCDs` goes a bit further but then you get `ImportError: libpylonbase-5.0.12.so: cannot open shared object file: No such file or directory`.  I think that you might need to have `/opt/pylon5/lib` (or `/opt/pylon5/lib64`) in your `LD_LIBRARY_PATH` (not just `/opt/pylon5`).

**Comment by PhilLAL** [comment]
Indeed! Adding this to ${LD_LIBRARY_PATH} allows to start LimaCCDs, thank you.
