### ISSUE TITLE
[doc] links update

### ISSUE THREAD

**Issue by PhilLAL** [esrf-bliss/Lima#83]
Hi,
reading the new documentation (https://lima-doc.readthedocs.io), I noticed that several links could be changed/fixed since the doc changed recently.
I made a list here, hoping this will help:
- in https://lima-doc.readthedocs.io/en/latest/requirements.html#python-dependencies, the link to Lima should be fixed to the new doc. This should be done for every Lima link so a search & replace should do the job
- in https://lima-doc.readthedocs.io/en/latest/requirements.html#pytango-server-dependencies, the link to libtango is dead, I do not know what the good link
- in https://lima-doc.readthedocs.io/en/latest/install_tango_device_server.html#server-setup, the link to tango is dead and should be http://www.tango-controls.org/ (with a "s") 
- in https://lima-doc.readthedocs.io/en/latest/supported_cameras.html#supported-cameras several detectors are not listed (see https://github.com/esrf-bliss/Lima/issues/79)
- in https://lima-doc.readthedocs.io/en/latest/applications/tango/python/doc/plugins/bpm.html#note the link to `bpm webserver application` needs an account to esrf gitlab
- in https://lima-doc.readthedocs.io/en/latest/plugin/index.html#camera-device there is a link to DS guidelines which has been integrated into the doc since then, so it seems to me it could be changed to https://tango-controls.readthedocs.io/en/latest/development/device-api/ds-guideline/

Happy new year.

**Comment by sdebionne** [comment]
Hi Phil,
All the best for 2019 and thanks for the bug report. The broken links are fixed and the updated doc should be published soon.

**Comment by PhilLAL** [comment]
Hi @sdebionne, it seems in the updated page following detectors are not listed in the pages list https://lima1.readthedocs.io/en/latest/supported_cameras.html#windows-only and https://lima1.readthedocs.io/en/latest/supported_cameras.html#linux-only and https://lima1.readthedocs.io/en/latest/supported_cameras.html#windows-and-linux :
- lambda 
- espia
- hexitec
- imxpad
- mythen
- mythen3
Perhaps it is just the name which is not the same.
Same spirit, Andor SDK2 and Andor SDK3 are perhaps the same that Andor and Andor 3 (for packages).

Regards.
