### ISSUE TITLE
conda installation for development 

### ISSUE THREAD

**Issue by PhilLAL** [esrf-bliss/Lima#84]
Hi guys,
I followed steps described int "Install Conda" (wget -nv https://download.opensuse.org/repositories/isv:ownCloud:desktop:client-2.4.3/Ubuntu_16.10/Release.key -O Release.key
sudo apt-key add - < Release.key
sudo apt-get update) part but it fails:

```
conda install lima-core
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - lima-core

Current channels:

  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/linux-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/pro/linux-64
  - https://repo.anaconda.com/pkgs/pro/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

In https://lima-doc.readthedocs.io/en/latest/build_install.html#install-binary-packages it is written to use a specific channel, perhaps should it be added and used here?

Regards.

**Comment by PhilLAL** [comment]
Hi again, 
perhaps I missed some information. If so, could you please tell me to let me to go further?
Thank you.

**Comment by sdebionne** [comment]
Hi Phil,
You are correct, the ESRF BCU channel is missing in your command:

```
conda install -c esrf-bcu lima-core 
```

**Comment by PhilLAL** [comment]
Thank Seb.
Visiting url https://anaconda.org/esrf-bcu/, I saw that there is a `lima-camera-basler` , ` lima-camera-pco` and `lima-camera-simulator`.
Does it mean packages are currently compiled or that other camera are not installed through packages?

**Comment by PhilLAL** [comment]
Sorry Sam :)
Thank you for the information.

**Comment by sdebionne** [comment]
Hi,
I have just uploaded processlib 1.6.0, that should fix some dependency issues. @smaluli Don't give up, I am sure we can help you! And `conda install --channel esrf-bcu lima-camera-basler-tango` should work out of the boxe.

**Comment by smaluli** [comment]
Marvellous!
Thank you Samuel, it works. I just have to configure the Jive wizard now; and maybe try this on a Windows environment.

**Comment by sdebionne** [comment]
Glad to hear that! @PhilLAL How is it going for you Phil? Can I close this issue?

**Comment by PhilLAL** [comment]
Hi,
to check this, I redo the steps from the beginning:
- download miniconda: `wget -c https://repo.anaconda.com/miniconda/Miniconda2-latest-Linux-x86_64.sh`
- install miniconda: `./Miniconda2-latest-Linux-x86_64.sh`
- reload the environment variables: `source ~/.bashrc`
- install lima basler: `conda install --channel esrf-bcu lima-camera-basler-tango`
- launch LimaCCDs : `LimaCCDs 1` and follow the doc to add the device into the database

So it seems to work, thank you.
