### ISSUE TITLE
[doc] installation method for binary packages

### ISSUE THREAD

**Issue by PhilLAL** [esrf-bliss/Lima#85]
Hello,
reading https://lima-doc.readthedocs.io/en/latest/build_install.html I imagine that perhaps some virtual environment could be useful to suggest in the doc here.
Just an idea, and I did not tested it, but I though perhaps you would be interested of this external sight into the doc. ^^

**Comment by sdebionne** [comment]
Hi Phil, sure we could mention the use of a dedicated conda environment for our lima packages. This is actually the way we deploy at ESRF (one env per camera wherever the same backend computer is used for multiple cameras).

```bash
conda create -n my-camera-env
conda activate my-camera-env
conda install -c esrf-bcu lima-camera-xxx
```

Did you checkout the doc about [building the cameras using conda toolset and libraries](https://lima-doc.readthedocs.io/en/latest/plugin/index.html#install-conda)? I would be happy to get your feedback.

**Comment by PhilLAL** [comment]
Yes, absolutly, this was what makes me think about it. :)

About this install step https://lima-doc.readthedocs.io/en/latest/build_install.html#install-binary-packages, I don't get the difference between `lima-camera-basler` and `lima-camera-basler-tango`.

I understand now LImA can work without TANGO, but if I work with TANGO, could I need `lima-camera-basler` and if yes, when?

**Comment by sdebionne** [comment]
If you work with tango, all you need is the tango package -that will in turn get the camera plugin as a runtime dependency and so on.

```
lima-camera-basler-tango |-> lima-camera-basler -> lima-core -> processlib
                         |-> lima-tango-server -> pytango
```

**Comment by PhilLAL** [comment]
Ok, thank you for the explanation :)

**Comment by PhilLAL** [comment]
Hi, 
I suggest to include an explanation into the doc (https://lima1.readthedocs.io/en/latest/build_install.html#install-binary-packages) to make it clear for the newcomer what is the difference. 
I get the dependency but I'm not sure what is the content of each package so I'm not sure how to say it.

**Comment by PhilLAL** [comment]
Hello,
discussing on this topic with some colleagues, we're not sure to understand what is included into `lima-camera-basler-tango` and in `lima-camera-basler`.

When it is written a "fully loaded LImA and all its dependencies with the Basler camera plugin and SDK" is included, does it mean Pylon (for Basler) is included for example?

**Comment by sdebionne** [comment]
Hi,

`lima-camera-basler-tango` itself is just the Basler camera plugin of LimaCCDs (the Tango Device Server), a file named `Basler.py`.

When installed, it also pull all its dependencies:

```
                                                | -> pylon-sdk
lima-camera-basler-tango |-> lima-camera-basler | -> lima-core | -> processlib -> gsl
                         |                                     | -> hdf5, tiff, libconfig, ...
                         |-> lima-tango-server  | -> pytango -> tango -> zmq...
                                                | -> boost-python
```

No more ascii art.

What I mean by "fully loaded LImA" is that the conda package of LImA was built with all options (and dependencies) ON.

**Comment by PhilLAL** [comment]
Great, it is even better than I though since it installs also pylon!
Thanks for the explanation Samuel. :)

**Comment by sdebionne** [comment]
`pylon-sdk` installs the user-space libraries of Pylon, not the drivers. Depending on the camera, you may have to install  the driver with the Pylon SDK installer (of the same version of Pylon). Windows and Linux use different Pylon versions. And Pylon 5.2 is not compatible: the low-level API we use in the plugin was removed.

**Comment by laurent-claustre** [comment]
you're right Samuel, but the lima basler plugin is only supporting GigE camera models. So far for Linux you can only trust on the pylon-sdk conda package.
For windows, you musst install pylon, because it will install some drivers to configure the GigE network adapter connected to your camera:
![win-pylon-driver](https://user-images.githubusercontent.com/16047419/54614372-93491e00-4a5c-11e9-8e3b-4c3458e599ca.jpg)

**Comment by PhilLAL** [comment]
Laurent made me wonder: I read that only GigE Basler have been tested but since only GigE Basler are supported, do you think USB Basler connected through USB to ethernet converter could work?

**Comment by laurent-claustre** [comment]
I don't know. I did test in the past an usb3 ACE camera, but the code was never been merged with mainstream. It will need some refactoring work to both work for GigE and USB.
