### ISSUE TITLE
[doc] LimaCCDs properties description

### ISSUE THREAD

**Issue by PhilLAL** [esrf-bliss/Lima#86]
Hi,
I see that the property list appears into Python TANGO server section (https://lima-doc.readthedocs.io/en/latest/applications/tango/python/doc/index.html#property)
However, it seems to me this section title let the user think this section is only for Python users.

Another section title (or section) would probably be more clear for new users which do not consider themselves as python users. :)

While installing a basler device, following the old tutorial (https://lima-doc.readthedocs.io/en/latest/install_tango_device_server.html#example-of-plugin-server-setup-basler-detector).
I have several suggestions:
- a link on this page to the page describing properties (https://lima-doc.readthedocs.io/en/latest/applications/tango/python/doc/index.html#property) can be useful for new user
- I discovered some properties actually asked by jive wizard (UserInstrumentName and SavingMaxConcurrentWriting) but which are not in the list https://lima-doc.readthedocs.io/en/latest/applications/tango/python/doc/index.html#property
Perhaps this list should be updated? 
- I do not see neither LimaViewer into my environment. I heard this is used only for test, so perhaps it has disappeared?

**Comment by sdebionne** [comment]
Agreed. The fact that the tango device server implementation is in python is rather an implementation detail. I'll see what I can do improve the docs with your suggestions.

**Comment by PhilLAL** [comment]
Hi, it seems these suggestions are not included into the code proposed in yuelongyu, am I wrong?

**Comment by PhilLAL** [comment]
Hi @sdebionne, I wonder if I missed those improvements or if they have not been yet implemented?
Cheers
