### ISSUE TITLE
offline installation

### ISSUE THREAD

**Issue by PhilLAL** [esrf-bliss/Lima#87]
Hello,
finalizing my test report of november pilatus tests, I would like to know if there is a way to download esrf-bcu channel packages through wget/curl.

The goal is to understand if we can simply prepare some offline installation or if is too painfull to loose time on this topic.

Regards.

**Comment by sdebionne** [comment]
You can get the packages using wget but you need to "guess the url":

```
wget https://anaconda.org/esrf-bcu/lima-core/1.8.0rc1/download/linux-64/lima-core-1.8.0rc1-py36ha8d69ae_12.tar.bz2
```

Conda has an offline install mode but I have never used it and I am not sure how it works with the dependencies:

```
conda install --offline lima-core-1.8.0rc1-py36ha8d69ae_12.tar.bz2
```

**Comment by PhilLAL** [comment]
From https://docs.conda.io/projects/continuumio-conda/en/latest/configuration.html it seems to allow installing from local files. 
It needs so to have download the tar.gz from a online PC and then copy them to the offline PC.
This is what I've done when I missed a Internet connection, except that I did not guess the URL ;)
