### ISSUE TITLE
Cannot Create/Launch LimaViewer Device 

### ISSUE THREAD

**Issue by hayg25** [esrf-bliss/Lima#88]
Dear All, 
I have created a LimaViewer device using LimaViewer.py. I followed your documentation located in https://lima-doc.readthedocs.io/en/latest/install_tango_device_server.html. 
When I started the device server I have the following error : 
``` 
Traceback (most recent call last):
  File "/home/tangodiag/anaconda2/bin/LimaViewer.py", line 263, in <module>
    main()
  File "/home/tangodiag/anaconda2/bin/LimaViewer.py", line 257, in main
    except PyTango.DevFailed(e):
NameError: global name 'e' is not defined
```
I have installed the packages in anaconda 2.7 on ubuntu 18.04 

Thanks for the feedback.

**Comment by hayg25** [comment]
Hi @laurent-claustre ,
I updated the Lima-tango-server as you suggested. I have now problems when declaring my Basler camera. 
See in python : 
```python
In [1]: from Lima import Basler
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-cea49ceb9d2a> in <module>()
----> 1 from Lima import Basler

/home/tangodiag/anaconda2/lib/python2.7/site-packages/Lima/Basler/__init__.py in <module>()
     21 ############################################################################
     22 from Lima import Core
---> 23 from limabasler import Basler as _B
     24 globals().update(_B.__dict__)

ImportError: /home/tangodiag/anaconda2/lib/python2.7/site-packages/../../liblimabasler.so.1.8: undefined symbol: _ZN4lima11ExcDebProxyC1EPNS_9TDebProxyILb1EEE
```
May be need also a newer version of : 
lima-camera-basler        1.8.0rc4         py27ha8d69ae_0    esrf-bcu

btw I am working at ThomX (LAL, Orsay) 

Cheers, 
Hayg

**Comment by laurent-claustre** [comment]
Hi Hayg,

Are you sure you have installed the latest lima-core package ? version 1.8.0rc10 
I did test on my own, it works fine, this is the list of the lima packages I got:
(lima_py2) lid00limace:~ % conda list |grep lima
# packages in environment at /users/blissadm/conda/miniconda/envs/lima_py2:
lima-camera-basler        1.8.0rc4         py27ha8d69ae_0    http://bcu-ci.esrf.fr/stable
lima-camera-basler-tango  1.8.0rc3                      0    http://bcu-ci.esrf.fr/stable
lima-core                 1.8.0rc10        py27ha8d69ae_0    esrf-bcu
lima-tango-server         1.8.0rc6                      0    http://bcu-ci.esrf.fr/stable

**Comment by hayg25** [comment]
Dear @laurent-claustre , 
the installation works fine, using : 
```
conda install --channel esrf-bcu lima-camera-basler
conda install --channel esrf-bcu lima-camera-basler-tango
```
and it installed me all as : 
```
      ▶  $ conda list | grep -i lima
lima-camera-basler        1.8.0rc4         py27ha8d69ae_0    esrf-bcu
lima-camera-basler-tango  1.8.0rc4                      0    esrf-bcu
lima-core                 1.8.0rc10        py27ha8d69ae_0    esrf-bcu
lima-tango-server         1.8.0rc9                      0    esrf-bcu
```
But I don't know where to find **LimaViewer**  as it should be use  to create the LimaViewer Ds. 
For now I created it myself from the python : 
```python
#!/usr/bin/env python
from Lima.Server.LimaViewer import main
main()
```

**Comment by hayg25** [comment]
Hi @laurent-claustre , 
so I started the Ds as described in the documentation. 
I have a  Basler camera which works fine using Pylon. 
When I start the Tango Ds, I have the following error messages : 
```
 (/opt/conda/conda-bld/lima-core_1548256228709/work/control/src/CtControl.cpp:791)-Error: Exception(Error): Frame(s) not available yet [thrown]
 (/opt/conda/conda-bld/lima-core_1548256228709/work/control/src/CtShutter.cpp:153)-Error: Exception(Error): No shutter capability [thrown]
 7f33fe7fc700 *Application*Lima.Server.LimaCCDs::LimaCCDs::read_acc_saturated_cblevel-Error: Accumulation threshold plugins not loaded
```
I would like at least to see in live mode, using the lima liveviewer class. It failed to work. 

Thanks for the feedback, 
Hayg

**Comment by hayg25** [comment]
Hi again, 
playing with the packet size I get read of the previous error messages and the camera seems to work. 
I still have a continuous message : No shutter capability [thrown]
but recently, after I changed the camera, I got the following message using LimaViewer : 
```
('-------> Received a DevFailed exception:', DevFailed(args = (DevError(desc = 'Exception: Hardware: setExpTime(/opt/conda/conda-bld/lima-camera-basler_1548237311771/work/src/BaslerCamera.cpp, 1055): Error: Value = 1 must be equal or greater than Min = 24.\n', origin = '  File "/home/guler/anaconda2/lib/python2.7/site-packages/Lima/Core/Debug.py", line 64, in real_fn\n    return new_fn(*arg, **kw)\n  File "/home/guler/anaconda2/lib/python2.7/site-packages/Lima/Server/LimaCCDs.py", line 1644, in prepareAcq\n    self.__control.prepareAcq()\n', reason = 'PyDs_PythonError', severity = tango._tango.ErrSeverity.ERR), DevError(desc = 'Failed to execute command_inout on device lima/limaccd/1, command prepareAcq', origin = 'Connection::command_inout()', reason = 'API_CommandFailed', severity = tango._tango.ErrSeverity.ERR))))
```

Thanks

**Comment by laurent-claustre** [comment]
Hi, 
forget about shutter capability msg, it just means the camera does not support this capability. This is because your client application is reading the shutter_  attributes like shutter_mode. I can add an issue to change the LimaCCDs server to to export those attributes if the shutter capability is not supported by the camera.

About the last exception, why do you mean by "after I changed the camera", it seems your camera only supports a exposure time greater than 24 seconds.???

**Comment by hayg25** [comment]
Hi, 
concerning the last exception I don't understand how to remove this limit ... is there a parameter I could set in PyTango ?

**Comment by laurent-claustre** [comment]
Did you change something on your camera using PylonViewer app, like exposure mode, autoexposure ...
This 24 sec minimum exposure is really a hardware limitiation returned by the camera, so lima just check the limits before setting to the hardware. To check you can read with PyTango the attribute **valid_ranges** : min_exposure, max_exposure, min_latency, max_latency

**Comment by hayg25** [comment]
Very strange indeed, it seems to be fixed even in pylon. The featured properties indicate minimum exposure time = 24s. And apparently it cannot be modified ... 
May be (I suspect) the problem comes from the camera itself, or more precisely the power cable which has probably not properly be done. If you confirm that  the featured values for the exposure are fixed, so I should look into the cabling.

**Comment by laurent-claustre** [comment]
you could try a factory reset as well to restore default configuration. I do not see why powersupply can affect internal configuration.
