### ISSUE TITLE
[doc] update of the (new) doc url into search engines

### ISSUE THREAD

**Issue by PhilLAL** [esrf-bliss/Lima#90]
Hi, 
the doc url has been updated into the github (https://lima1.rtfd.io) but the old link still appears in several search engins. Perhaps it could be updated faster by a manual operation?
Cheers

**Comment by sdebionne** [comment]
We will be killing lima.blissgarden.org today and wait for the Google crawler to update the rank of the `lima1.rtfd.io` domain. There nothing that we can about it as we don't own the main `rtfd.io` domain.
Thanks for the report!
