### ISSUE TITLE
list of possible error messages

### ISSUE THREAD

**Issue by PhilLAL** [esrf-bliss/Lima#92]
Reading the issues and based on my first experience, I wonder if a list of error message which can be encountered would not be an interesting help for newcomers.

Of course, error message could be classified according to 
- OS
- module : Lima or camera-type, perhaps even they can be specific to some cameras (I think for example to Basler and jumbo frames).

Would you think such a list could be placed into a specific part of the doc?
Regards

**Comment by laurent-claustre** [comment]
Hi Philippe,
good suggestion, feel free to make a PR in that sense.

**Comment by PhilLAL** [comment]
Thanks, I do not have currently some error message to propose but it's good to know a PR is the good way to do it. I did hesitate with an issue. :)
