### ISSUE TITLE
Take images at maximum speed 

### ISSUE THREAD

**Issue by hayg25** [esrf-bliss/Lima#97]
Dear all, 
I am playing around with a Basler camera and I  would need to take data at the maximum possible speed through Tango. 
```python 
dev_limaccd.acq_expo_time = 0.01 #The exposure time of the image, Default is 1 second
dev_limaccd.acq_nb_frames = 50  #Number of frames to be acquired, Default is 1 frame
dev_limaccd.saving_format='Edf'
dev_limaccd.saving_directory='/home/tangodiag/OUT'
dev_limaccd.saving_prefix='tst_'
dev_limaccd.saving_suffix = '.edf'
dev_limaccd.prepareAcq()
dev_limaccd.startAcq()


t0 = dt.datetime.now()
last_img = dev_limaccd.last_image_ready	
print 'last image --- ',last_img,dev_limaccd.last_image_saved	
read_image=-1
while last_img != dev_limaccd.acq_nb_frames-1:
    read_image += 1
    last_img = dev_limaccd.last_image_ready	
    time.sleep(0.05)
    t=dt.datetime.now()
    print 'last image --- ',read_image,last_img,dev_limaccd.last_image_ready,dev_limaccd.last_image_saved,t-t0
    
for i in range(0,dev_limaccd.acq_nb_frames):
    print i
    img = dev_limaccd.readImage(i)    
    dev_limaccd.writeImage(i)
```
Using that options I could reach 10-15 Hz. I would need to approach 50 ... 
How could I improve acq speed through Tango ? 

Thanks for the feedback

**Comment by laurent-claustre** [comment]
Hi Guler
so after our phone discussion,  as I tell you you should use the auto_frame mode for saving instead of 
doing a manual saving in you last 'for i in ...' loop
just set the attribute as below:

dev_limaccd.saving_mode = "auto_frame"

to stop auto saving, switch back the attribute to manual mode:
dev_limaccd.saving_mode  = "manual"


About your new issue with the Scout model camera, I need to test here, if I can find a Scout camera at ESRF. It seems we did break something maybe by upgrading to Pylon5.
I will keep you inform.
Cheers
Laurent

**Comment by laurent-claustre** [comment]
Hi Guler,
I did test with a Scout scA1000-30gm, this morning and it worked fine. 50 images 0.01s exposure.
Did you  Scout camera already work with Lima?
You may have a parameter which does not allow lima to start the acquisition. Below a snapshot of
PylonViewerApp for the "Acquisition Controls" parameters after the Lima acquisition above (1ms 50frames).

![scout-acq-controls](https://user-images.githubusercontent.com/16047419/54414874-dcb30980-46fa-11e9-8f9b-7bad6d171914.jpg)

**Comment by hayg25** [comment]
Hi @laurent-claustre , 
using dev_limaccd.saving_mode = "auto_frame"  I managed to reach 70 Hz image saving with a Basler ACE 640. 
Concerning the Scout, my last tests showed an image split into 4 parts ... did someone experienced that problem ?

**Comment by laurent-claustre** [comment]
so did fix the problem with the Scout and the non ending acquisition?
Could you paste an image here to have a look?
Is your Scout camera connected via a network switch and not directly to the computer NIC?

**Comment by hayg25** [comment]
Hi @laurent-claustre , 
I made some new tests after I updated lima packages through Conda. I am now using the 1.8 versions. 
And very strange : I managed to take 100 images without any error. Event the LiveView work fine. 
I will make additional tests but my SCA640-70gm work perfectly now. 
Concerning the configurations : 
1- I switch my laptop to Jumbo Frames (mtu 9000)
2- Frame transmission  delay : 10 us
    Inter packet delay : 100 us
    Packet size : 2000 
I will report on using other cameras

**Comment by hayg25** [comment]
Hi @laurent-claustre , 
I have made tests on another Scout, same model and I have more problems :
I could save 100 images but split in 4 as attached ... 
and LimaCCDs makes error in the end. 
**I kept the same config as previously.** 

Error message on LimaCCDs : 
```
[2019/03/25 18:30:01.275245] 7fb418e88700 (/opt/conda/conda-bld/lima-camera-basler_1549640215705/work/src/BaslerCamera.cpp:657)-Error: No image acquired! Error code : 0xhex= e1000014 Error description : The buffer was incompletely grabbed. This can be caused by performance problems of the network hardware used, i.e. network adapter, switch, or ethernet cable. To fix this, try increasing the camera's Inter-Packet Delay in the Transport Layer category to reduce the required bandwidth, and adjust the camera's Packet Size setting to the highest supported frame size.
```
![ImageProblemScout](https://user-images.githubusercontent.com/7941588/54941139-66997880-4f2c-11e9-8776-eeab4abc8af9.png)

**Comment by laurent-claustre** [comment]
Hi, why do you set packet size to 2000 if your NIC is set to mtu 9000, the camera packet size should be set to the maximum supported by the NIC, so 9000.
But please, answer to my last question, is your camera directly connected to your laptop or via a network switch ?

**Comment by hayg25** [comment]
Hi,
ok I will try with 9000. I took it smaller in order to prevent errors concerning the previous error I reported. So yes I forgot about my connection : The Camera is connected to my laptop directly via RJ45 cable.

**Comment by hayg25** [comment]
Hi @laurent-claustre ,
I compared feature files from pylon for both Scout : the one OK and the one with split images as posted previously and acquisition problems. 
The first difference I see is : 
-  Device version = 3.1.10 Camera OK  
-  Device version = 3.1.1   Camera with problems 
The camera with Device version = 3.1.10 has also more features : 
SequenceSetTotalNumber	2
SequenceSetIndex	0
SequenceSetExecutions	1
SequenceAdvanceMode	Auto

Is there a way to update the Device version ? (I suppose it corresponds to the camera driver)

Thx, 
Hayg

**Comment by hayg25** [comment]
Hi @laurent-claustre , 
I had discussions with people from Lima concerning our camera that did not worked properly, in particular one Scout (out of 3) and one Ace. We realized that the ones who did not word had missing **sequencer** feature. 
Event with the latest firmware on my cameras ... 
The method to enable this feature is to use PylonViewer : select FeatureSet and choose Full. 
Then reboot your camera (Switch OFF / ON ), and the feature is there, and the camera works fine with Lima. 

Many thx again, 
Cheers, 
Hayg
